# Generated by Django 4.2.17 on 2024-12-10 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_people_passed', models.IntegerField(default=0)),
                ('current_people', models.IntegerField(default=0)),
                ('total_accidents', models.IntegerField(default=0)),
                ('total_events', models.IntegerField(default=0)),
                ('alerts_per_hour', models.JSONField(default=dict)),
            ],
        ),
    ]
