# Generated by Django 4.2.17 on 2024-12-10 13:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_dashboard_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
